ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=0)

      DOUBLE PRECISION MDL_MU,MDL_ME,MDL_MC,MDL_MT,MDL_MD,MDL_MH
     $ ,MDL_MMU,MDL_MW,MDL_MS,MDL_MZ,MDL_MB,MDL_MTA

      COMMON/MASSES/ MDL_MU,MDL_ME,MDL_MC,MDL_MT,MDL_MD,MDL_MH,MDL_MMU
     $ ,MDL_MW,MDL_MS,MDL_MZ,MDL_MB,MDL_MTA


      DOUBLE PRECISION MDL_WZ,MDL_WH,MDL_WW,MDL_WT

      COMMON/WIDTHS/ MDL_WZ,MDL_WH,MDL_WW,MDL_WT


      DOUBLE COMPLEX GC_36, GC_56, GC_59

      COMMON/COUPLINGS/ GC_36, GC_56, GC_59

