C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Gamma(3,2,1)
C     
      SUBROUTINE FFV1PZ1_3(F1, F2, COUP, M3, W3,V3)
      IMPLICIT NONE
      INCLUDE '../MODEL/input.inc'
      INCLUDE '../MODEL/coupl.inc'
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      COMPLEX*16 FCT0
      COMPLEX*16 FCT1
      REAL*8 M3
      REAL*8 P3(0:3)
      COMPLEX*16 TMP0
      COMPLEX*16 TMP1
      COMPLEX*16 V3(6)
      REAL*8 W3
      COMPLEX*16 DENOM
      V3(1) = +F1(1)+F2(1)
      V3(2) = +F1(2)+F2(2)
      P3(0) = -DBLE(V3(1))
      P3(1) = -DBLE(V3(2))
      P3(2) = -DIMAG(V3(2))
      P3(3) = -DIMAG(V3(1))
      TMP0 = (F1(3)*(F2(5)*(P3(0)+P3(3))+F2(6)*(P3(1)+CI*(P3(2))))
     $ +(F1(4)*(F2(5)*(P3(1)-CI*(P3(2)))+F2(6)*(P3(0)-P3(3)))+(F1(5)
     $ *(F2(3)*(P3(0)-P3(3))-F2(4)*(P3(1)+CI*(P3(2))))+F1(6)*(F2(3)*(
     $ -P3(1)+CI*(P3(2)))+F2(4)*(P3(0)+P3(3))))))
      TMP1 = (P3(0)*P3(0)-P3(1)*P3(1)-P3(2)*P3(2)-P3(3)*P3(3))
      FCT0 = 1D0/(M3*M3)
      FCT1 = ((M3*(-M3+CI*(W3))+TMP1))**(2D0)
      DENOM = COUP/(FCT1)
      V3(3)= DENOM*(-M3)*MDL_DWZ*(F2(5)*F1(3)+F2(6)*F1(4)+F2(3)*F1(5)
     $ +F2(4)*F1(6)-P3(0)*TMP0*FCT0)
      V3(4)= DENOM*M3*MDL_DWZ*(F2(6)*F1(3)+F2(5)*F1(4)+P3(1)*TMP0*FCT0
     $ -F2(4)*F1(5)-F2(3)*F1(6))
      V3(5)= DENOM*M3*MDL_DWZ*(+CI*(F2(6)*F1(3)+F2(3)*F1(6))-CI*(F2(5)
     $ *F1(4)+F2(4)*F1(5))+P3(2)*TMP0*FCT0)
      V3(6)= DENOM*M3*MDL_DWZ*(F2(5)*F1(3)+F2(4)*F1(6)+P3(3)*TMP0*FCT0
     $ -F2(6)*F1(4)-F2(3)*F1(5))
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Gamma(3,2,1)
C     
      SUBROUTINE FFV1_3PZ1_3(F1, F2, COUP1, COUP2, M3, W3,V3)
      IMPLICIT NONE
      INCLUDE '../MODEL/input.inc'
      INCLUDE '../MODEL/coupl.inc'
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP1
      COMPLEX*16 COUP2
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      REAL*8 M3
      REAL*8 P3(0:3)
      COMPLEX*16 V3(6)
      COMPLEX*16 VTMP(6)
      REAL*8 W3
      COMPLEX*16 DENOM
      INTEGER*4 I
      CALL FFV1PZ1_3(F1,F2,COUP1,M3,W3,V3)
      CALL FFV3PZ1_3(F1,F2,COUP2,M3,W3,VTMP)
      DO I = 3, 6
        V3(I) = V3(I) + VTMP(I)
      ENDDO
      END


