ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=0)

      DOUBLE PRECISION MDL_MW,MDL_MD,MDL_MT,MDL_MH,MDL_MS,MDL_MB
     $ ,MDL_MC,MDL_MU,MDL_ME,MDL_MZ,MDL_MMU,MDL_MTA

      COMMON/MASSES/ MDL_MW,MDL_MD,MDL_MT,MDL_MH,MDL_MS,MDL_MB,MDL_MC
     $ ,MDL_MU,MDL_ME,MDL_MZ,MDL_MMU,MDL_MTA


      DOUBLE PRECISION MDL_WZ,MDL_WW,MDL_WT,MDL_WH

      COMMON/WIDTHS/ MDL_WZ,MDL_WW,MDL_WT,MDL_WH


      DOUBLE COMPLEX GC_14, GC_15, GC_24, GC_35, GC_36, GC_56, GC_59,
     $  GC_84, GC_85

      COMMON/COUPLINGS/ GC_14, GC_15, GC_24, GC_35, GC_36, GC_56,
     $  GC_59, GC_84, GC_85

