ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=0)

      DOUBLE PRECISION MDL_MS,MDL_MB,MDL_MZ,MDL_MW,MDL_MTA,MDL_MU
     $ ,MDL_MD,MDL_MH,MDL_MT,MDL_ME,MDL_MC,MDL_MMU

      COMMON/MASSES/ MDL_MS,MDL_MB,MDL_MZ,MDL_MW,MDL_MTA,MDL_MU,MDL_MD
     $ ,MDL_MH,MDL_MT,MDL_ME,MDL_MC,MDL_MMU


      DOUBLE PRECISION MDL_WH,MDL_WW,MDL_WT,MDL_WZ

      COMMON/WIDTHS/ MDL_WH,MDL_WW,MDL_WT,MDL_WZ


      DOUBLE COMPLEX GC_24, GC_58, GC_61, GC_84, GC_85, GC_88, GC_89

      COMMON/COUPLINGS/ GC_24, GC_58, GC_61, GC_84, GC_85, GC_88, GC_89

