ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=0)

      DOUBLE PRECISION MDL_MTA,MDL_MT,MDL_MZ,MDL_MU,MDL_MMU,MDL_MD
     $ ,MDL_MW,MDL_MS,MDL_MH,MDL_ME,MDL_MB,MDL_MC

      COMMON/MASSES/ MDL_MTA,MDL_MT,MDL_MZ,MDL_MU,MDL_MMU,MDL_MD
     $ ,MDL_MW,MDL_MS,MDL_MH,MDL_ME,MDL_MB,MDL_MC


      DOUBLE PRECISION MDL_WT,MDL_WH,MDL_WZ,MDL_WW

      COMMON/WIDTHS/ MDL_WT,MDL_WH,MDL_WZ,MDL_WW


      DOUBLE COMPLEX GC_14, GC_15, GC_36, GC_56, GC_59, GC_84, GC_85

      COMMON/COUPLINGS/ GC_14, GC_15, GC_36, GC_56, GC_59, GC_84, GC_85

