ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=0)

      DOUBLE PRECISION MDL_MW,MDL_MTA,MDL_MD,MDL_MC,MDL_MT,MDL_MS
     $ ,MDL_MZ,MDL_MU,MDL_MH,MDL_MB,MDL_MMU,MDL_ME

      COMMON/MASSES/ MDL_MW,MDL_MTA,MDL_MD,MDL_MC,MDL_MT,MDL_MS,MDL_MZ
     $ ,MDL_MU,MDL_MH,MDL_MB,MDL_MMU,MDL_ME


      DOUBLE PRECISION MDL_WH,MDL_WT,MDL_WW,MDL_WZ

      COMMON/WIDTHS/ MDL_WH,MDL_WT,MDL_WW,MDL_WZ


      DOUBLE COMPLEX GC_56, GC_59, GC_84, GC_85

      COMMON/COUPLINGS/ GC_56, GC_59, GC_84, GC_85

