ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=0)

      DOUBLE PRECISION MDL_MB,MDL_MH,MDL_MZ,MDL_MD,MDL_MW,MDL_MMU
     $ ,MDL_MS,MDL_MT,MDL_ME,MDL_MTA,MDL_MC,MDL_MU

      COMMON/MASSES/ MDL_MB,MDL_MH,MDL_MZ,MDL_MD,MDL_MW,MDL_MMU,MDL_MS
     $ ,MDL_MT,MDL_ME,MDL_MTA,MDL_MC,MDL_MU


      DOUBLE PRECISION MDL_WH,MDL_WT,MDL_WW,MDL_WZ

      COMMON/WIDTHS/ MDL_WH,MDL_WT,MDL_WW,MDL_WZ


      DOUBLE COMPLEX GC_36, GC_56, GC_59

      COMMON/COUPLINGS/ GC_36, GC_56, GC_59

