ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of SMEFTsim_general_alphaScheme_UFO'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_6162 = ', GC_6162
      WRITE(*,2) 'GC_6294 = ', GC_6294
      WRITE(*,2) 'GC_6341 = ', GC_6341
      WRITE(*,2) 'GC_6345 = ', GC_6345
      WRITE(*,2) 'GC_6348 = ', GC_6348
      WRITE(*,2) 'GC_6365 = ', GC_6365
      WRITE(*,2) 'GC_6383 = ', GC_6383
