ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of HEFT_UFO_Real-Z_2c_test'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_56 = ', GC_56
      WRITE(*,2) 'GC_59 = ', GC_59
      WRITE(*,2) 'GC_84 = ', GC_84
      WRITE(*,2) 'GC_85 = ', GC_85
