ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=0)

      DOUBLE PRECISION MDL_MTA,MDL_MS,MDL_MB,MDL_MH,MDL_MT,MDL_MW
     $ ,MDL_MMU,MDL_MC,MDL_MZ,MDL_ME,MDL_MU,MDL_MD

      COMMON/MASSES/ MDL_MTA,MDL_MS,MDL_MB,MDL_MH,MDL_MT,MDL_MW
     $ ,MDL_MMU,MDL_MC,MDL_MZ,MDL_ME,MDL_MU,MDL_MD


      DOUBLE PRECISION MDL_WZ,MDL_WT,MDL_WW,MDL_WH

      COMMON/WIDTHS/ MDL_WZ,MDL_WT,MDL_WW,MDL_WH


      DOUBLE COMPLEX GC_14, GC_15, GC_36, GC_56, GC_59, GC_84, GC_85

      COMMON/COUPLINGS/ GC_14, GC_15, GC_36, GC_56, GC_59, GC_84, GC_85

