ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of SMEFTsim_general_MwScheme_UFO'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_5910 = ', GC_5910
      WRITE(*,2) 'GC_6173 = ', GC_6173
      WRITE(*,2) 'GC_6187 = ', GC_6187
      WRITE(*,2) 'GC_6308 = ', GC_6308
      WRITE(*,2) 'GC_6361 = ', GC_6361
      WRITE(*,2) 'GC_6379 = ', GC_6379
