ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=0)

      DOUBLE PRECISION MDL_MH,MDL_ME,MDL_MD,MDL_MW,MDL_MMU,MDL_MC
     $ ,MDL_MS,MDL_MTA,MDL_MU,MDL_MZ,MDL_MB,MDL_MT

      COMMON/MASSES/ MDL_MH,MDL_ME,MDL_MD,MDL_MW,MDL_MMU,MDL_MC,MDL_MS
     $ ,MDL_MTA,MDL_MU,MDL_MZ,MDL_MB,MDL_MT


      DOUBLE PRECISION MDL_WH,MDL_WW,MDL_WT,MDL_WZ

      COMMON/WIDTHS/ MDL_WH,MDL_WW,MDL_WT,MDL_WZ


      DOUBLE COMPLEX GC_14, GC_15, GC_36, GC_56, GC_59, GC_84, GC_85

      COMMON/COUPLINGS/ GC_14, GC_15, GC_36, GC_56, GC_59, GC_84, GC_85

