ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of HEFT_UFO_Real'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_14 = ', GC_14
      WRITE(*,2) 'GC_15 = ', GC_15
      WRITE(*,2) 'GC_24 = ', GC_24
      WRITE(*,2) 'GC_35 = ', GC_35
      WRITE(*,2) 'GC_36 = ', GC_36
      WRITE(*,2) 'GC_56 = ', GC_56
      WRITE(*,2) 'GC_59 = ', GC_59
      WRITE(*,2) 'GC_84 = ', GC_84
      WRITE(*,2) 'GC_85 = ', GC_85
