ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of SMEFT_UFO_ZandAVertex-ZAvertex_4c'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_24 = ', GC_24
      WRITE(*,2) 'GC_58 = ', GC_58
      WRITE(*,2) 'GC_61 = ', GC_61
      WRITE(*,2) 'GC_84 = ', GC_84
      WRITE(*,2) 'GC_85 = ', GC_85
      WRITE(*,2) 'GC_88 = ', GC_88
      WRITE(*,2) 'GC_89 = ', GC_89
