ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=0)

      DOUBLE PRECISION MDL_MTA,MDL_MMU,MDL_MB,MDL_MS,MDL_MC,MDL_MW
     $ ,MDL_MZ,MDL_MW1,MDL_MT,MDL_MU,MDL_MH,MDL_MZ1,MDL_MH1,MDL_MD
     $ ,MDL_MT1,MDL_ME

      COMMON/MASSES/ MDL_MTA,MDL_MMU,MDL_MB,MDL_MS,MDL_MC,MDL_MW
     $ ,MDL_MZ,MDL_MW1,MDL_MT,MDL_MU,MDL_MH,MDL_MZ1,MDL_MH1,MDL_MD
     $ ,MDL_MT1,MDL_ME


      DOUBLE PRECISION MDL_WT1,MDL_WZ1,MDL_WH1,MDL_WZ,MDL_WT,MDL_WW
     $ ,MDL_WH,MDL_WW1

      COMMON/WIDTHS/ MDL_WT1,MDL_WZ1,MDL_WH1,MDL_WZ,MDL_WT,MDL_WW
     $ ,MDL_WH,MDL_WW1


      DOUBLE COMPLEX GC_5910, GC_6173, GC_6187, GC_6308, GC_6361,
     $  GC_6379

      COMMON/COUPLINGS/ GC_5910, GC_6173, GC_6187, GC_6308, GC_6361,
     $  GC_6379

